apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels: 
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: ptanmay0071/onlinemart-client:latest
        ports:
        - name: client-port
          containerPort: 4200
