apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7.25
        ports:
        - name: mysqldb-port
          containerPort: 3306
        volumeMounts:
            - name: mysql
              mountPath: /var/lib/mysql
        env: 
         - name: MYSQL_DATABASE
           valueFrom:
            secretKeyRef:
              name: dbsecret
              key: mysqldbname

         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
             secretKeyRef:
               name: dbsecret
               key: mysqldb-pass
      volumes:
      - name: mysql
        persistentVolumeClaim:
          claimName: mysql  