apiVersion: v1
kind: Secret
metadata:
  name: dbsecret
type: Opaque
data:
  mysqldb-pass: ZW1hcnRkYnBhc3M= 
  rmq-pass: Z3Vlc3Q=
  
  mongodbname: epoc
  mongo_uri: mongodb://mongo:27017/epoc
  mysqldbname: books
